## Load user dynamic jack autoswitcher for Intel SOF
wireplumber.components = [
  {
    name = "sof-autoswitch.lua"
    type = "script/lua"
    provides = "custom.sof-autoswitch"
  }
]

wireplumber.profiles = {
  main = {
    custom.sof-autoswitch = required
  }
}

## Configure sink node priority order:
## Headphones (1500) > Internal Speaker (1200) > External HDMI Displays (600)
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*.HiFi__HDMI.*"
      }
    ]
    actions = {
      update-props = {
        priority.driver  = 600
        priority.session = 600
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_output.*.HiFi__Speaker.*"
      }
    ]
    actions = {
      update-props = {
        priority.driver  = 1200
        priority.session = 1200
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_output.*.HiFi__Headphones.*"
      }
    ]
    actions = {
      update-props = {
        priority.driver  = 1500
        priority.session = 1500
      }
    }
  }
]
