-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Acer Technologies KA222Q E3 65340FCD13W01",
  mode = "1920x1080@74.97",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Acer Technologies KA222Q E3 65340FCD13W01", default = true, persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:Acer Technologies KA222Q E3 65340FCD13W01" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Acer Technologies KA222Q E3 65340FCD13W01" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Acer Technologies KA222Q E3 65340FCD13W01" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Acer Technologies KA222Q E3 65340FCD13W01" })
