-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Samsung Display Corp. 0x4181",
  mode = "2880x1800@90.00",
  position = "0x0",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Samsung Display Corp. 0x4181", default = true, persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:Samsung Display Corp. 0x4181" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Samsung Display Corp. 0x4181" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Samsung Display Corp. 0x4181" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Samsung Display Corp. 0x4181" })
